# Generated by Django 5.1 on 2024-08-27 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CloaksMart", "0002_test"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CloaksListings",
        ),
    ]
