# Generated by Django 4.2.15 on 2024-09-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CloaksMart", "0006_filteredlistings_animal_wrap"),
    ]

    operations = [
        migrations.AddField(
            model_name="filteredlistings",
            name="archer_ears",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="filteredlistings",
            name="archer_hair",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="filteredlistings",
            name="arm_style",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="filteredlistings",
            name="beard",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
