# Generated by Django 4.2.15 on 2024-09-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CloaksMart", "0007_filteredlistings_archer_ears_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filteredlistings",
            old_name="clan_type",
            new_name="type_cloak",
        ),
    ]
