# Generated by Django 4.2.15 on 2024-09-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CloaksMart", "0008_rename_clan_type_filteredlistings_type_cloak"),
    ]

    operations = [
        migrations.AddField(
            model_name="filteredlistings",
            name="chain",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="filteredlistings",
            name="chest",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="filteredlistings",
            name="cloak",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="filteredlistings",
            name="eyewear",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="filteredlistings",
            name="face_mask",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="filteredlistings",
            name="headband",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="filteredlistings",
            name="headgear",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="filteredlistings",
            name="mouth",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="filteredlistings",
            name="shoulder_gear",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="filteredlistings",
            name="smoke",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="filteredlistings",
            name="symbol",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="filteredlistings",
            name="warpaint",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
