# Generated by Django 4.2.15 on 2024-09-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CloaksMart", "0009_filteredlistings_chain_filteredlistings_chest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filteredlistings",
            name="num_traits",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
