# Generated by Django 4.2.15 on 2024-09-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CloaksMart", "0010_filteredlistings_num_traits"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCloaks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=200)),
            ],
        ),
    ]
