# Generated by Django 4.2.15 on 2024-10-22 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CloaksMart", "0015_holder"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Holder",
        ),
    ]
